apiVersion: v1
kind: Service
metadata:
  name: valaxy-service
  labels:
    app: valaxy-devops-project  ## This should match the label present in deployment file under metadata section metadata  
spec:
  selector:
    app: valaxy-devops-project  ## This should match the label present in deployment file under metadata section template/metadata   
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
